-- Intentionally left as a no-op.
-- The previous version deleted one hard-coded recurring assignment series and its assignments.
-- Data cleanup must not live in repeatable source-controlled migrations because it can
-- delete production/customer data when migrations are replayed in a new environment.
